# Enriched Properties DataFrame

Reads all properties from the SQLite database and parses the `extra_features` JSON column into structured columns using the feature parser (74 features total: 41 v1 + 23 v2 + 10 v3).

In [1]:
import sys
from pathlib import Path

# Add project root to path so we can import app modules
PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(PROJECT_ROOT))

import sqlite3
import json
import pandas as pd
from app.feature_parser import parse_all_features
from app.constants import FEATURE_PARSER_KEYS

DB_PATH = PROJECT_ROOT / "uk_house_prices.db"

# Load all properties with extra_features from the database
conn = sqlite3.connect(str(DB_PATH))
df = pd.read_sql_query(
    "SELECT id, address, postcode, property_type, bedrooms, bathrooms, "
    "extra_features, url FROM properties "
    "WHERE extra_features IS NOT NULL",
    conn,
)
conn.close()

print(f"Loaded {len(df):,} properties with extra_features")
print(f"Feature parser keys: {len(FEATURE_PARSER_KEYS)} features")
df.head(3)

Loaded 205,371 properties with extra_features
Feature parser keys: 74 features

,id,address,postcode,property_type,bedrooms,bathrooms,extra_features,url
0,1,"Flat 6, Ivory House, East Smithfield, London E...",E1W 1AT,FLAT,1,1,[],https://www.rightmove.co.uk/house-prices/detai...
1,2,"Flat 23, Ivory House, East Smithfield, London ...",E1W 1AT,FLAT,1,1,[],https://www.rightmove.co.uk/house-prices/detai...
2,3,"Flat 25, Ivory House, East Smithfield, London ...",E1W 1AT,FLAT,4,0,[],https://www.rightmove.co.uk/house-prices/detai...

## Parse extra_features into structured columns (74 features)

In [2]:
# Parse extra_features for each row
parsed = df["extra_features"].apply(parse_all_features).apply(pd.Series)

# Join parsed columns to original dataframe
enriched = pd.concat([df, parsed], axis=1)

NEW_COLS = list(parsed.columns)

# Split into v1, v2, v3 features
V1_FEATURES = [
    "epc_rating", "council_tax_band", "chain_free", "parking", "garden",
    "heating", "double_glazed", "lease_type", "lease_years", "receptions",
    "furnished", "period_property", "utility_room", "conservatory", "ensuite",
    "cloakroom", "floor_level", "sq_ft", "service_charge", "ground_rent",
    "wooden_floors", "gym", "lift", "dining_room", "ev_charger", "fireplace",
    "study", "shower_room", "fitted_wardrobes", "new_build", "concierge",
    "swimming_pool", "air_conditioning", "solar_panels", "loft",
    "entrance_hall", "white_goods", "bay_window", "distance_to_station",
    "intercom", "split_level",
]
V2_FEATURES = [
    "cellar", "roof_terrace", "high_ceilings", "open_plan", "gated",
    "purpose_built", "refurbished", "duplex", "penthouse", "own_front_door",
    "private_entrance", "bike_storage", "cul_de_sac", "conservation_area",
    "annexe", "views", "underground_parking", "allocated_parking",
    "garden_facing", "property_era", "condition", "kitchen_type",
    "listed_building",
]
V3_FEATURES = [c for c in NEW_COLS if c not in V1_FEATURES and c not in V2_FEATURES]

print(f"Enriched: {len(enriched):,} rows, {len(enriched.columns)} columns")
print(f"  v1 features: {len(V1_FEATURES)}")
print(f"  v2 features: {len(V2_FEATURES)}")
print(f"  v3 features: {len(V3_FEATURES)} — {V3_FEATURES}")
enriched[["address", "postcode"] + V2_FEATURES + V3_FEATURES].head(10)

Enriched: 205,371 rows, 82 columns
  v1 features: 41
  v2 features: 23
  v3 features: 10 — ['extended', 'outbuilding', 'potential_to_extend', 'walk_in_wardrobe', 'wet_room', 'integrated_appliances', 'side_access', 'video_entry', 'separate_living_room', 'laminate_flooring']

,address,postcode,cellar,roof_terrace,high_ceilings,open_plan,gated,purpose_built,refurbished,duplex,...,extended,outbuilding,potential_to_extend,walk_in_wardrobe,wet_room,integrated_appliances,side_access,video_entry,separate_living_room,laminate_flooring
0,"Flat 6, Ivory House, East Smithfield, London E...",E1W 1AT,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,"Flat 23, Ivory House, East Smithfield, London ...",E1W 1AT,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,"Flat 25, Ivory House, East Smithfield, London ...",E1W 1AT,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,"Flat 30, Ivory House, East Smithfield, London ...",E1W 1AT,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,"Flat 32, Ivory House, East Smithfield, London ...",E1W 1AT,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,"Flat 29, Ivory House, East Smithfield, London ...",E1W 1AT,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6,"Flat 34, Ivory House, East Smithfield, London ...",E1W 1AT,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
7,"Flat 15, Ivory House, East Smithfield, London ...",E1W 1AT,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,"Flat 4, Ivory House, East Smithfield, London E...",E1W 1AT,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9,"Flat 21, Ivory House, East Smithfield, London ...",E1W 1AT,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

## Fill rates per column (all 74 features)

In [3]:
fill_rates = enriched[NEW_COLS].notna().sum().to_frame("filled")
fill_rates["total"] = len(enriched)
fill_rates["pct"] = (fill_rates["filled"] / fill_rates["total"] * 100).round(1)
fill_rates["version"] = fill_rates.index.map(
    lambda x: "v3 NEW" if x in V3_FEATURES else ("v2" if x in V2_FEATURES else "v1")
)
fill_rates = fill_rates.sort_values("pct", ascending=False)

print(f"{'Feature':<25} {'Filled':>8} {'Total':>8} {'Fill%':>7}  Version")
print("-" * 65)
for feat, row in fill_rates.iterrows():
    print(f"{feat:<25} {row['filled']:>8,.0f} {row['total']:>8,.0f} {row['pct']:>6.1f}%  {row['version']}")

# Summary
v1_f = fill_rates[fill_rates["version"] == "v1"]["filled"].sum()
v2_f = fill_rates[fill_rates["version"] == "v2"]["filled"].sum()
v3_f = fill_rates[fill_rates["version"] == "v3 NEW"]["filled"].sum()
total_filled = v1_f + v2_f + v3_f
print(f"\nTotal feature values extracted: {total_filled:,.0f}")
print(f"  v1: {v1_f:,.0f}")
print(f"  v2: {v2_f:,.0f}")
print(f"  v3 (new): {v3_f:,.0f}")
print(f"  New (v2+v3): {v2_f+v3_f:,.0f} ({(v2_f+v3_f)/total_filled*100:.1f}%)")

Feature                     Filled    Total   Fill%  Version
-----------------------------------------------------------------
garden                      79,699  205,371   38.8%  v1
parking                     31,157  205,371   15.2%  v1
kitchen_type                29,760  205,371   14.5%  v2
epc_rating                  23,321  205,371   11.4%  v1
floor_level                 21,657  205,371   10.5%  v1
open_plan                   16,627  205,371    8.1%  v2
receptions                  15,178  205,371    7.4%  v1
lease_type                  14,613  205,371    7.1%  v1
chain_free                  14,286  205,371    7.0%  v1
sq_ft                       12,144  205,371    5.9%  v1
ensuite                     11,820  205,371    5.8%  v1
furnished                   10,934  205,371    5.3%  v1
concierge                   10,280  205,371    5.0%  v1
garden_facing                9,449  205,371    4.6%  v2
dining_room                  8,830  205,371    4.3%  v1
shower_room                  8,548  205,371    4.2%  v1
refurbished                  7,541  205,371    3.7%  v2
cloakroom                    7,607  205,371    3.7%  v1
heating                      7,166  205,371    3.5%  v1
wooden_floors                6,920  205,371    3.4%  v1
property_era                 7,053  205,371    3.4%  v2
condition                    5,444  205,371    2.7%  v2
roof_terrace                 5,126  205,371    2.5%  v2
lift                         4,883  205,371    2.4%  v1
council_tax_band             4,886  205,371    2.4%  v1
period_property              5,008  205,371    2.4%  v1
double_glazed                4,720  205,371    2.3%  v1
potential_to_extend          4,466  205,371    2.2%  v3 NEW
utility_room                 4,451  205,371    2.2%  v1
gym                          4,270  205,371    2.1%  v1
split_level                  3,962  205,371    1.9%  v1
study                        3,557  205,371    1.7%  v1
gated                        3,584  205,371    1.7%  v2
separate_living_room         3,461  205,371    1.7%  v3 NEW
cellar                       3,474  205,371    1.7%  v2
extended                     3,212  205,371    1.6%  v3 NEW
loft                         2,790  205,371    1.4%  v1
allocated_parking            2,649  205,371    1.3%  v2
underground_parking          2,671  205,371    1.3%  v2
fitted_wardrobes             2,768  205,371    1.3%  v1
views                        2,498  205,371    1.2%  v2
high_ceilings                2,469  205,371    1.2%  v2
entrance_hall                2,230  205,371    1.1%  v1
white_goods                  2,073  205,371    1.0%  v1
integrated_appliances        1,976  205,371    1.0%  v3 NEW
purpose_built                1,999  205,371    1.0%  v2
lease_years                  1,938  205,371    0.9%  v1
fireplace                    1,633  205,371    0.8%  v1
swimming_pool                1,575  205,371    0.8%  v1
conservatory                 1,691  205,371    0.8%  v1
distance_to_station          1,492  205,371    0.7%  v1
outbuilding                  1,137  205,371    0.6%  v3 NEW
bike_storage                 1,322  205,371    0.6%  v2
own_front_door               1,130  205,371    0.6%  v2
private_entrance             1,065  205,371    0.5%  v2
cul_de_sac                   1,083  205,371    0.5%  v2
new_build                      755  205,371    0.4%  v1
air_conditioning               769  205,371    0.4%  v1
side_access                    891  205,371    0.4%  v3 NEW
duplex                         742  205,371    0.4%  v2
penthouse                      636  205,371    0.3%  v2
conservation_area              550  205,371    0.3%  v2
bay_window                     647  205,371    0.3%  v1
service_charge                 587  205,371    0.3%  v1
walk_in_wardrobe               575  205,371    0.3%  v3 NEW
intercom                       523  205,371    0.3%  v1
laminate_flooring              453  205,371    0.2%  v3 NEW
video_entry                    325  205,371    0.2%  v3 NEW
listed_building                350  205,371    0.2%  v2
ground_rent                    299  205,371    0.1%  v1
annexe                         189  205,371    0.1%  v2
ev_charger                     113  205,371    0.1%  v1
wet_room                       159  205,371    0.1%  v3 NEW
solar_panels                    98  205,371    0.0%  v1

Total feature values extracted: 465,944
  v1: 341,878
  v2: 107,411
  v3 (new): 16,655
  New (v2+v3): 124,066 (26.6%)

## Value distributions for v2 + v3 features

In [4]:
for col in V2_FEATURES + V3_FEATURES:
    filled = enriched[col].dropna()
    if len(filled) == 0:
        continue
    print(f"\n{'='*50}")
    print(f"{col} ({len(filled):,} filled / {len(enriched):,} total = {len(filled)/len(enriched)*100:.1f}%)")
    print(f"{'='*50}")
    print(filled.value_counts().head(10).to_string())

==================================================
cellar (3,474 filled / 205,371 total = 1.7%)
==================================================
cellar
True    3474

==================================================
roof_terrace (5,126 filled / 205,371 total = 2.5%)
==================================================
roof_terrace
True    5126

==================================================
high_ceilings (2,469 filled / 205,371 total = 1.2%)
==================================================
high_ceilings
True    2469

==================================================
open_plan (16,627 filled / 205,371 total = 8.1%)
==================================================
open_plan
True    16627

==================================================
gated (3,584 filled / 205,371 total = 1.7%)
==================================================
gated
True    3584

==================================================
purpose_built (1,999 filled / 205,371 total = 1.0%)
==================================================
purpose_built
True    1999

==================================================
refurbished (7,541 filled / 205,371 total = 3.7%)
==================================================
refurbished
True    7541

==================================================
duplex (742 filled / 205,371 total = 0.4%)
==================================================
duplex
True    742

==================================================
penthouse (636 filled / 205,371 total = 0.3%)
==================================================
penthouse
True    636

==================================================
own_front_door (1,130 filled / 205,371 total = 0.6%)
==================================================
own_front_door
True    1130

==================================================
private_entrance (1,065 filled / 205,371 total = 0.5%)
==================================================
private_entrance
True    1065

==================================================
bike_storage (1,322 filled / 205,371 total = 0.6%)
==================================================
bike_storage
True    1322

==================================================
cul_de_sac (1,083 filled / 205,371 total = 0.5%)
==================================================
cul_de_sac
True    1083

==================================================
conservation_area (550 filled / 205,371 total = 0.3%)
==================================================
conservation_area
True    550

==================================================
annexe (189 filled / 205,371 total = 0.1%)
==================================================
annexe
True    189

==================================================
views (2,498 filled / 205,371 total = 1.2%)
==================================================
views
True    2498

==================================================
underground_parking (2,671 filled / 205,371 total = 1.3%)
==================================================
underground_parking
True    2671

==================================================
allocated_parking (2,649 filled / 205,371 total = 1.3%)
==================================================
allocated_parking
True    2649

==================================================
garden_facing (9,449 filled / 205,371 total = 4.6%)
==================================================
garden_facing
South    4883
West     4245
East      314
North       7

==================================================
property_era (7,053 filled / 205,371 total = 3.4%)
==================================================
property_era
Victorian    5440
Edwardian    1078
Art Deco      390
Georgian      145

==================================================
condition (5,444 filled / 205,371 total = 2.7%)
==================================================
condition
Excellent     3086
Immaculate    1258
Good          1095
Fair             5

==================================================
kitchen_type (29,760 filled / 205,371 total = 14.5%)
==================================================
kitchen_type
Kitchen Diner    12290
Open Plan         8506
Separate          5462
Eat-in            3502

==================================================
listed_building (350 filled / 205,371 total = 0.2%)
==================================================
listed_building
True    350

==================================================
extended (3,212 filled / 205,371 total = 1.6%)
==================================================
extended
True    3212

==================================================
outbuilding (1,137 filled / 205,371 total = 0.6%)
==================================================
outbuilding
True    1137

==================================================
potential_to_extend (4,466 filled / 205,371 total = 2.2%)
==================================================
potential_to_extend
True    4466

==================================================
walk_in_wardrobe (575 filled / 205,371 total = 0.3%)
==================================================
walk_in_wardrobe
True    575

==================================================
wet_room (159 filled / 205,371 total = 0.1%)
==================================================
wet_room
True    159

==================================================
integrated_appliances (1,976 filled / 205,371 total = 1.0%)
==================================================
integrated_appliances
True    1976

==================================================
side_access (891 filled / 205,371 total = 0.4%)
==================================================
side_access
True    891

==================================================
video_entry (325 filled / 205,371 total = 0.2%)
==================================================
video_entry
True    325

==================================================
separate_living_room (3,461 filled / 205,371 total = 1.7%)
==================================================
separate_living_room
True    3461

==================================================
laminate_flooring (453 filled / 205,371 total = 0.2%)
==================================================
laminate_flooring
True    453

In [5]:
# v1 feature distributions (for reference)
for col in V1_FEATURES:
    filled = enriched[col].dropna()
    if len(filled) == 0:
        continue
    print(f"\n{'='*50}")
    print(f"{col} ({len(filled):,} filled / {len(enriched):,} total = {len(filled)/len(enriched)*100:.1f}%)")
    print(f"{'='*50}")
    print(filled.value_counts().head(10).to_string())

==================================================
epc_rating (23,321 filled / 205,371 total = 11.4%)
==================================================
epc_rating
G    19245
D     1506
C     1444
B      569
E      511
F       35
A       11

==================================================
council_tax_band (4,886 filled / 205,371 total = 2.4%)
==================================================
council_tax_band
D    1289
C    1047
E    1003
F     586
G     517
B     252
H     128
A      64

==================================================
chain_free (14,286 filled / 205,371 total = 7.0%)
==================================================
chain_free
True     14242
False       44

==================================================
parking (31,157 filled / 205,371 total = 15.2%)
==================================================
parking
Parking       14906
Off-street     9965
Garage         5353
Driveway        933

==================================================
garden (79,699 filled / 205,371 total = 38.8%)
==================================================
garden
Garden             30055
Private Garden     16177
Balcony            15469
Terrace             7700
Communal Garden     7098
Patio               3200

==================================================
heating (7,166 filled / 205,371 total = 3.5%)
==================================================
heating
Gas Central        2724
Underfloor         1762
Central Heating    1459
Other              1152
Electric             69

==================================================
double_glazed (4,720 filled / 205,371 total = 2.3%)
==================================================
double_glazed
True    4720

==================================================
lease_type (14,613 filled / 205,371 total = 7.1%)
==================================================
lease_type
Leasehold            5483
Share of Freehold    4763
Freehold             4367

==================================================
lease_years (1,938 filled / 205,371 total = 0.9%)
==================================================
lease_years
999.0    182
125.0    148
150.0     36
100.0     34
99.0      34
900.0     31
175.0     26
990.0     25
91.0      24
170.0     23

==================================================
receptions (15,178 filled / 205,371 total = 7.4%)
==================================================
receptions
2.0     6633
1.0     5299
3.0     1717
4.0      399
17.0     118
5.0       84
16.0      69
20.0      64
18.0      62
15.0      55

==================================================
furnished (10,934 filled / 205,371 total = 5.3%)
==================================================
furnished
Furnished         5222
Flexible          4405
Part Furnished    1307

==================================================
period_property (5,008 filled / 205,371 total = 2.4%)
==================================================
period_property
True    5008

==================================================
utility_room (4,451 filled / 205,371 total = 2.2%)
==================================================
utility_room
True    4451

==================================================
conservatory (1,691 filled / 205,371 total = 0.8%)
==================================================
conservatory
True    1691

==================================================
ensuite (11,820 filled / 205,371 total = 5.8%)
==================================================
ensuite
True    11820

==================================================
cloakroom (7,607 filled / 205,371 total = 3.7%)
==================================================
cloakroom
True    7607

==================================================
floor_level (21,657 filled / 205,371 total = 10.5%)
==================================================
floor_level
Ground      6931
First       4946
Upper       2955
Top         2470
Second      2011
Third       1606
Basement     738

==================================================
sq_ft (12,144 filled / 205,371 total = 5.9%)
==================================================
sq_ft
1000.0    273
2000.0    151
800.0     137
900.0     126
700.0     118
500.0      92
1100.0     90
1500.0     86
1200.0     85
600.0      74

==================================================
service_charge (587 filled / 205,371 total = 0.3%)
==================================================
service_charge
1200.0    15
2000.0    11
1000.0     9
1800.0     8
1100.0     7
1300.0     6
3000.0     6
1500.0     6
2600.0     6
1600.0     6

==================================================
ground_rent (299 filled / 205,371 total = 0.1%)
==================================================
ground_rent
10.0     43
100.0    24
0.0      22
200.0    20
500.0    17
250.0    17
150.0    15
300.0    15
50.0     10
350.0     8

==================================================
wooden_floors (6,920 filled / 205,371 total = 3.4%)
==================================================
wooden_floors
True    6920

==================================================
gym (4,270 filled / 205,371 total = 2.1%)
==================================================
gym
True    4270

==================================================
lift (4,883 filled / 205,371 total = 2.4%)
==================================================
lift
True    4883

==================================================
dining_room (8,830 filled / 205,371 total = 4.3%)
==================================================
dining_room
True    8830

==================================================
ev_charger (113 filled / 205,371 total = 0.1%)
==================================================
ev_charger
True    113

==================================================
fireplace (1,633 filled / 205,371 total = 0.8%)
==================================================
fireplace
True    1633

==================================================
study (3,557 filled / 205,371 total = 1.7%)
==================================================
study
True    3557

==================================================
shower_room (8,548 filled / 205,371 total = 4.2%)
==================================================
shower_room
True    8548

==================================================
fitted_wardrobes (2,768 filled / 205,371 total = 1.3%)
==================================================
fitted_wardrobes
True    2768

==================================================
new_build (755 filled / 205,371 total = 0.4%)
==================================================
new_build
True    755

==================================================
concierge (10,280 filled / 205,371 total = 5.0%)
==================================================
concierge
True    10280

==================================================
swimming_pool (1,575 filled / 205,371 total = 0.8%)
==================================================
swimming_pool
True    1575

==================================================
air_conditioning (769 filled / 205,371 total = 0.4%)
==================================================
air_conditioning
True    769

==================================================
solar_panels (98 filled / 205,371 total = 0.0%)
==================================================
solar_panels
True    98

==================================================
loft (2,790 filled / 205,371 total = 1.4%)
==================================================
loft
True    2790

==================================================
entrance_hall (2,230 filled / 205,371 total = 1.1%)
==================================================
entrance_hall
True    2230

==================================================
white_goods (2,073 filled / 205,371 total = 1.0%)
==================================================
white_goods
True    2073

==================================================
bay_window (647 filled / 205,371 total = 0.3%)
==================================================
bay_window
True    647

==================================================
distance_to_station (1,492 filled / 205,371 total = 0.7%)
==================================================
distance_to_station
0.3    317
0.4    247
0.2    235
0.5    176
0.1    151
0.6    138
0.7     92
0.8     44
0.9     19
1.0     18

==================================================
intercom (523 filled / 205,371 total = 0.3%)
==================================================
intercom
True    523

==================================================
split_level (3,962 filled / 205,371 total = 1.9%)
==================================================
split_level
True    3962

## Save enriched dataframe

In [6]:
output_path = PROJECT_ROOT / "sales_data" / "enriched_properties.parquet"
output_path.parent.mkdir(parents=True, exist_ok=True)
enriched.to_parquet(output_path, engine="pyarrow", compression="snappy", index=False)
print(f"Saved to {output_path}")
print(f"  {len(enriched):,} rows x {len(enriched.columns)} columns")
print(f"  Columns: {list(enriched.columns)}")

Saved to C:\dev\rightmove-api\sales_data\enriched_properties.parquet
  205,371 rows x 82 columns
  Columns: ['id', 'address', 'postcode', 'property_type', 'bedrooms', 'bathrooms', 'extra_features', 'url', 'epc_rating', 'council_tax_band', 'chain_free', 'parking', 'garden', 'heating', 'double_glazed', 'lease_type', 'lease_years', 'receptions', 'furnished', 'period_property', 'utility_room', 'conservatory', 'ensuite', 'cloakroom', 'floor_level', 'sq_ft', 'service_charge', 'ground_rent', 'wooden_floors', 'gym', 'lift', 'dining_room', 'ev_charger', 'fireplace', 'study', 'shower_room', 'fitted_wardrobes', 'new_build', 'concierge', 'swimming_pool', 'air_conditioning', 'solar_panels', 'loft', 'entrance_hall', 'white_goods', 'bay_window', 'distance_to_station', 'intercom', 'split_level', 'cellar', 'roof_terrace', 'high_ceilings', 'open_plan', 'gated', 'purpose_built', 'refurbished', 'duplex', 'penthouse', 'own_front_door', 'private_entrance', 'bike_storage', 'cul_de_sac', 'conservation_area', 'annexe', 'views', 'underground_parking', 'allocated_parking', 'garden_facing', 'property_era', 'condition', 'kitchen_type', 'listed_building', 'extended', 'outbuilding', 'potential_to_extend', 'walk_in_wardrobe', 'wet_room', 'integrated_appliances', 'side_access', 'video_entry', 'separate_living_room', 'laminate_flooring']